# This is a basic workflow to help you get started with Actions

name: Sample GitHub Actions workflow

on:
  push:
    branches: 
      - main
    tags:
      - v1        # Push events to v1 tag
      - v2.*      # Push events to v1.0, v1.1, and v1.9 tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      # Setup a Java 
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1

      # Runs a set of commands using the runners shell
      - name: Github action Maven Project
        run: mvn -B package --file pom.xml
        
      # Check Target Folder 
      - name: Target Folder
        run: |
          cd target
          ls -a
